version: '2'
    
services:
    
  dpagent:
    image: dpagent-image
    hostname: dpagent
          
  hxehost:
    image: store/saplabs/hanaexpress:2.00.036.00.20190223.1
    hostname: hxe
    volumes:
      - hxedev:/hana/mounts
    command: --agree-to-sap-license --master-password ${HXE_MASTER_PASSWORD}
  
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    hostname: oracle
    volumes:
      - oracle-db:/ORCL

volumes:

  hxedev:
    external:
      name: hana-express
      
  oracle-db:
    external:
      name: oracle-db
