version: '2'
    
services:
  # Data Provisioning Agent Image
  dpagent:
    image: registry.howles.cloud/dpagent:2.4
    container_name: dpagent
    hostname: dpagent

  # SAP HANA Express DB-only Image
  hxehost:
    image: store/saplabs/hanaexpress:2.00.040.00.20190729.1
    container_name: hxe
    hostname: hxe
    ports:
      - 39041:39041 
      - 39017:39017
      - 39013:39013
      - 39015:39015
      - 8090:8090
    volumes:
      - hana-db:/hana/mounts
      
  # Oracle 12.2 Slim DB Image
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1-slim
    container_name: oracle
    hostname: oracle
    ports:
      - 1521:1521
    volumes:
      - oracle-db:/ORCL

  # Microsoft SQL Server Image
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: mssql
    hostname: mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "HXEHana1"
    ports:
      - "1433:1433/tcp"
    volumes:
      - mssql-db:/var/opt/mssql

# Persistent Volumes
volumes:
  hana-db:
    external:
      name: hana-db
      
  oracle-db:
    external:
      name: oracle-db

  mssql-db:
    external:
      name: mssql-db
